package interfaz_pl2;

import clases_pl2.Actividad;
import clases_pl2.DiaSemana;
import clases_pl2.Horario;
import clases_pl2.TipoActividad;
import java.io.IOException;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import persistencia.Gestor;
import java.util.ArrayList;
import clases_pl2.Sala;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Interfaz de actualización de actividades.
 * Se puede acceder a esta actividad desde adminInterface
 * @author david, Samuel
 */
public class ActualizarActividad extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ActualizarActividad.class.getName());
    private boolean operacionExitosa = false; // Empezamos asumiendo que no hay éxito
    private Actividad actividadOriginal;

    public ActualizarActividad(java.awt.Frame parent, boolean modal, Actividad act) {
        super(parent, modal);
        this.actividadOriginal = act;
        initComponents();
        
        // Forzamos el tamaño de los spinners (Me daban problemas con el Design de netbeans)
        java.awt.Dimension tamañoSpinner = new java.awt.Dimension(64, 26);
        jSpinnerHoraInicio.setPreferredSize(tamañoSpinner);
        jSpinnerMinutosInicio.setPreferredSize(tamañoSpinner);
        jSpinnerHoraFin.setPreferredSize(tamañoSpinner);
        jSpinnerMinutosFin.setPreferredSize(tamañoSpinner);
        
        for (int i = 0; i < TipoActividad.values().length; i++){
            this.jComboBoxTipo.addItem(TipoActividad.values()[i].getDescripcion());
        }
        
        // Ocultamos los campos especiales por defecto
        jLabelPrecio.setVisible(false);
        jFormattedTextFieldPrecio.setVisible(false);
        jLabelDescripcion.setVisible(false);
        jTextFieldDescrpcion.setVisible(false);
        
        // Rellenamos los datos si recibimos una actividad válida
        if (act != null) {
            jTextFieldTitulo.setText(act.getTitulo());
            if (act.getTipo() != null) jComboBoxTipo.setSelectedItem(act.getTipo().getDescripcion());
            jTextFieldMonitor.setText(act.getMonitor());
            jTextFieldSala.setText(act.getSala().getNombre());
            jSpinnerAforo.setValue(act.getSala().getAforoMaximo());
            
            //Cargamos la ruta de la imagen (si hay opcional)
            if (act.getRutaImagen() != null) {
                jTextFieldImagen.setText(act.getRutaImagen());
            }
            Horario horario = act.getHorario();
            if (horario != null) {
                jSpinnerHoraInicio.setValue(horario.getHoraInicio().getHour());
                jSpinnerMinutosInicio.setValue(horario.getHoraInicio().getMinute());
                jSpinnerHoraFin.setValue(horario.getHoraFin().getHour());
                jSpinnerMinutosFin.setValue(horario.getHoraFin().getMinute());
                
                jCheckBoxLunes.setSelected(horario.incluyeDia(DiaSemana.L));
                jCheckBoxMartes.setSelected(horario.incluyeDia(DiaSemana.M));
                jCheckBoxMiercoles.setSelected(horario.incluyeDia(DiaSemana.X));
                jCheckBoxJueves.setSelected(horario.incluyeDia(DiaSemana.J));
                jCheckBoxViernes.setSelected(horario.incluyeDia(DiaSemana.V));
                jCheckBoxSabado.setSelected(horario.incluyeDia(DiaSemana.S));
                jCheckBoxDomingo.setSelected(horario.incluyeDia(DiaSemana.D));
            }
            
            // Si la actividad que estamos editando ES especial, rellenamos y mostramos sus campos
            if (act.esEspecial()) {
                jCheckBoxActividadEspecial.setSelected(true);
                
                jLabelPrecio.setVisible(true);
                jFormattedTextFieldPrecio.setVisible(true);
                jLabelDescripcion.setVisible(true);
                jTextFieldDescrpcion.setVisible(true);
                
                // Hacemos el "cast" para poder acceder a getPrecio() y getDescripcion()
                clases_pl2.ActividadEspecial ae = (clases_pl2.ActividadEspecial) act;
                jFormattedTextFieldPrecio.setText(String.valueOf(ae.getPrecio()));
                jTextFieldDescrpcion.setText(ae.getDescripcion());
            }
        }
        
        this.pack(); // quede la ventana empaquetada (Antes daba problemas)
    }
    public boolean isOperacionExitosa() { //devolver datos de exito
        return operacionExitosa;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldMonitor = new javax.swing.JTextField();
        jTextFieldSala = new javax.swing.JTextField();
        jTextFieldImagen = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerAforo = new javax.swing.JSpinner();
        jSpinnerHoraInicio = new javax.swing.JSpinner();
        jSpinnerMinutosInicio = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerMinutosFin = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerHoraFin = new javax.swing.JSpinner();
        jCheckBoxLunes = new javax.swing.JCheckBox();
        jCheckBoxMartes = new javax.swing.JCheckBox();
        jCheckBoxMiercoles = new javax.swing.JCheckBox();
        jCheckBoxJueves = new javax.swing.JCheckBox();
        jCheckBoxViernes = new javax.swing.JCheckBox();
        jCheckBoxSabado = new javax.swing.JCheckBox();
        jCheckBoxDomingo = new javax.swing.JCheckBox();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAplicar = new javax.swing.JButton();
        jFormattedTextFieldPrecio = new javax.swing.JFormattedTextField();
        jTextFieldDescrpcion = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jCheckBoxActividadEspecial = new javax.swing.JCheckBox();
        jButtonExaminarImagen = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("JavaFit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Título:");

        jLabel4.setText("Monitor:");

        jLabel5.setText("Tipo:");

        jLabel6.setText("Sala:");

        jLabel7.setText("Días:");

        jLabel8.setText("Hora inicio:");

        jLabel9.setText("Hora fin:");

        jLabel10.setText("Imagen (Ruta):");

        jTextFieldTitulo.addActionListener(this::jTextFieldTituloActionPerformed);

        jComboBoxTipo.addActionListener(this::jComboBoxTipoActionPerformed);

        jLabel11.setText("Aforo:");

        jSpinnerAforo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerHoraInicio.setModel(new javax.swing.SpinnerNumberModel(6, 6, 23, 1));

        jSpinnerMinutosInicio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText(":");

        jSpinnerMinutosFin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jSpinnerMinutosFin.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText(":");

        jSpinnerHoraFin.setModel(new javax.swing.SpinnerNumberModel(6, 6, 23, 1));

        jCheckBoxLunes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxLunes.setText("L");
        jCheckBoxLunes.addActionListener(this::jCheckBoxLunesActionPerformed);

        jCheckBoxMartes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxMartes.setText("M");
        jCheckBoxMartes.addActionListener(this::jCheckBoxMartesActionPerformed);

        jCheckBoxMiercoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxMiercoles.setText("X");
        jCheckBoxMiercoles.addActionListener(this::jCheckBoxMiercolesActionPerformed);

        jCheckBoxJueves.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxJueves.setText("J");
        jCheckBoxJueves.addActionListener(this::jCheckBoxJuevesActionPerformed);

        jCheckBoxViernes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxViernes.setText("V");
        jCheckBoxViernes.addActionListener(this::jCheckBoxViernesActionPerformed);

        jCheckBoxSabado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxSabado.setText("S");
        jCheckBoxSabado.addActionListener(this::jCheckBoxSabadoActionPerformed);

        jCheckBoxDomingo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxDomingo.setText("D");
        jCheckBoxDomingo.addActionListener(this::jCheckBoxDomingoActionPerformed);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(this::jButtonCancelarActionPerformed);

        jButtonAplicar.setText("Aplicar");
        jButtonAplicar.addActionListener(this::jButtonAplicarActionPerformed);

        jFormattedTextFieldPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        jTextFieldDescrpcion.addActionListener(this::jTextFieldDescrpcionActionPerformed);

        jLabelDescripcion.setText("Descripcion:");

        jLabelPrecio.setText("Precio(€):");

        jCheckBoxActividadEspecial.setText("Actividad Especial (con precio)");
        jCheckBoxActividadEspecial.addActionListener(this::jCheckBoxActividadEspecialActionPerformed);

        jButtonExaminarImagen.setText("Examinar");
        jButtonExaminarImagen.addActionListener(this::jButtonExaminarImagenActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAplicar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxActividadEspecial)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldPrecio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDescrpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldSala, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel13)
                                                .addGap(3, 3, 3)
                                                .addComponent(jSpinnerMinutosFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSpinnerHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel12)
                                                .addGap(3, 3, 3)
                                                .addComponent(jSpinnerMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerAforo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldImagen))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxLunes)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxMartes)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxMiercoles)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxJueves)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxViernes)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxSabado)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxDomingo))
                                    .addComponent(jButtonExaminarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxLunes)
                    .addComponent(jCheckBoxMartes)
                    .addComponent(jCheckBoxMiercoles)
                    .addComponent(jCheckBoxJueves)
                    .addComponent(jCheckBoxViernes)
                    .addComponent(jCheckBoxSabado)
                    .addComponent(jCheckBoxDomingo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMinutosFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExaminarImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxActividadEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDescrpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAplicar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxLunesActionPerformed

    private void jCheckBoxMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMartesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMartesActionPerformed

    private void jCheckBoxMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMiercolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMiercolesActionPerformed

    private void jCheckBoxJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJuevesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxJuevesActionPerformed

    private void jCheckBoxViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxViernesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxViernesActionPerformed

    private void jCheckBoxSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSabadoActionPerformed

    private void jCheckBoxDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDomingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDomingoActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
        //Lógica de actualización de Datos
        Gestor gestor = Gestor.getInstancia();

        try {
            gestor.cargarDatos(); 
        } catch (IOException ex) {
            System.getLogger(ActualizarActividad.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (ClassNotFoundException ex) {
            System.getLogger(ActualizarActividad.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        try {
            // Horario - Recolección de días
            ArrayList<DiaSemana> dias = new ArrayList<DiaSemana>();
            if (this.jCheckBoxLunes.isSelected()){dias.add(DiaSemana.L);}
            if (this.jCheckBoxMartes.isSelected()){dias.add(DiaSemana.M);}
            if (this.jCheckBoxMiercoles.isSelected()){dias.add(DiaSemana.X);}
            if (this.jCheckBoxJueves.isSelected()){dias.add(DiaSemana.J);}
            if (this.jCheckBoxViernes.isSelected()){dias.add(DiaSemana.V);}
            if (this.jCheckBoxSabado.isSelected()){dias.add(DiaSemana.S);}
            if (this.jCheckBoxDomingo.isSelected()){dias.add(DiaSemana.D);}
            
            // Excepcion
            if (dias.isEmpty()){ throw new Exception("Debe tener por lo menos un día de la semana");}

            LocalTime inicio = LocalTime.of( (int) this.jSpinnerHoraInicio.getValue(), (int) this.jSpinnerMinutosInicio.getValue());
            LocalTime finalt = LocalTime.of( (int) this.jSpinnerHoraFin.getValue(), (int) this.jSpinnerMinutosFin.getValue());
            
            // Excepcion
            if (inicio.isAfter(finalt)){ throw new Exception("No puede terminar la actividad antes de que comience");}
            
            String titulo = jTextFieldTitulo.getText();
            // Excepcion
            if (titulo.isBlank()){ throw new Exception("Debe tener título");}
            
            String descripcionSeleccionada = (String) jComboBoxTipo.getSelectedItem();
            TipoActividad tipoactividad = null;

            // Buscamos qué enum tiene esa descripción (Para guardar los datos correctamente)
            for (TipoActividad tipo : TipoActividad.values()) {
                if (tipo.getDescripcion().equals(descripcionSeleccionada)) {
                    tipoactividad = tipo;
                    break; // Lo encontramos, salimos del bucle
                }
            }

            Horario horario = new Horario(dias, finalt, inicio); 
            
            Sala sala = new Sala(jTextFieldSala.getText(), (int) jSpinnerAforo.getValue());
            if (jTextFieldSala.getText().isBlank()){ throw new Exception("La sala debe tener título");}
            
            String monitor = jTextFieldMonitor.getText();
            if (monitor.isEmpty()){ throw new Exception("Debe tener un monitor asignado");}

            // Diferenciar entre actividad especial y básica
            Actividad nuevaActividad;
            if (jCheckBoxActividadEspecial.isSelected()) {
                String descripcion = jTextFieldDescrpcion.getText();
                if (descripcion.isBlank()) throw new Exception("La actividad especial debe tener una descripción.");
                
                double precio = 0.0;
                try {
                    String textoPrecio = jFormattedTextFieldPrecio.getText().replace("€", "").replace(",", ".").trim();
                    precio = Double.parseDouble(textoPrecio);
                } catch (Exception e) {
                    throw new Exception("El precio introducido no es válido.");
                }
                
                nuevaActividad = new clases_pl2.ActividadEspecial(precio, descripcion, 0, titulo, tipoactividad, sala, horario, monitor);
            } else {
                nuevaActividad = new Actividad(0, titulo, tipoactividad, sala, horario, monitor);
            }
            // guardar imagen (opcional)
            String rutaImagen = jTextFieldImagen.getText().trim();
            if (!rutaImagen.isEmpty()) {
                nuevaActividad.setRutaImagen(rutaImagen);
            }
            gestor.actualizarActividad(actividadOriginal.getId(), nuevaActividad);
            gestor.guardarDatos();
            this.operacionExitosa = true;
            JOptionPane.showMessageDialog(this, "La actividad ha sido actualizada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAplicarActionPerformed

    private void jTextFieldDescrpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescrpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescrpcionActionPerformed

    private void jCheckBoxActividadEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActividadEspecialActionPerformed
        boolean esEspecial = jCheckBoxActividadEspecial.isSelected();
        
        jLabelPrecio.setVisible(esEspecial);
        jFormattedTextFieldPrecio.setVisible(esEspecial);
        jLabelDescripcion.setVisible(esEspecial);
        jTextFieldDescrpcion.setVisible(esEspecial);
        
        this.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxActividadEspecialActionPerformed

    private void jButtonExaminarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExaminarImagenActionPerformed
        // Crear el fileChooser desde esta clase
        JFileChooser selectorArchivos = new JFileChooser();

        // que empiece desde carpeta user
        selectorArchivos.setCurrentDirectory(new java.io.File(System.getProperty("user.home")));

        // Solo acepta imagenes
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter(
            "Archivos de Imagen (*.jpg, *.jpeg, *.png)", "jpg", "jpeg", "png");

        // Aplicamos el filtro al selector
        selectorArchivos.setFileFilter(filtroImagen);

        int resultado = selectorArchivos.showOpenDialog(this);

        // Si el usuario le dio al botón "Abrir"
        if (resultado == JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = selectorArchivos.getSelectedFile();
            // Obtenemos la ruta absoluta
            String ruta = archivoSeleccionado.getAbsolutePath();
            // La escribimos en el campo de texto para que el usuario la vea y el programa la guarde
            jTextFieldImagen.setText(ruta);
        }
    }//GEN-LAST:event_jButtonExaminarImagenActionPerformed

    
    //He eliminado el método main ya que es necesaria tener una actividad para actualizar
    //Si quieres usar esta interfaz tienes que desde AdminInterface editar una actividad en el botón azul de abajo
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExaminarImagen;
    private javax.swing.JCheckBox jCheckBoxActividadEspecial;
    private javax.swing.JCheckBox jCheckBoxDomingo;
    private javax.swing.JCheckBox jCheckBoxJueves;
    private javax.swing.JCheckBox jCheckBoxLunes;
    private javax.swing.JCheckBox jCheckBoxMartes;
    private javax.swing.JCheckBox jCheckBoxMiercoles;
    private javax.swing.JCheckBox jCheckBoxSabado;
    private javax.swing.JCheckBox jCheckBoxViernes;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerAforo;
    private javax.swing.JSpinner jSpinnerHoraFin;
    private javax.swing.JSpinner jSpinnerHoraInicio;
    private javax.swing.JSpinner jSpinnerMinutosFin;
    private javax.swing.JSpinner jSpinnerMinutosInicio;
    private javax.swing.JTextField jTextFieldDescrpcion;
    private javax.swing.JTextField jTextFieldImagen;
    private javax.swing.JTextField jTextFieldMonitor;
    private javax.swing.JTextField jTextFieldSala;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
