/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz_pl2;

/**
 *
 * @author david
 */
public class ErrorCorreo extends javax.swing.JDialog {
    //private String TextoErrorS;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ErrorCorreo.class.getName());

    /**
     * Creates new form ErrorCorreo
     */
    public ErrorCorreo(java.awt.Frame parent, boolean modal, String TextoError) {
        super(parent, modal);
        initComponents();
        this.TextoError.setText("<html>" + TextoError + "</html>"); //Formateado en html para paso de línea
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloError = new javax.swing.JLabel();
        TextoError = new javax.swing.JLabel();
        OkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TituloError.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TituloError.setText("Error!");

        TextoError.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoError.setText("Tipo de Error");
        TextoError.setFocusable(false);
        TextoError.setMaximumSize(new java.awt.Dimension(150, 80));
        TextoError.setPreferredSize(new java.awt.Dimension(450, 90));
        TextoError.setRequestFocusEnabled(false);

        OkButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        OkButton.setText("OK");
        OkButton.addActionListener(this::OkButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TextoError, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(TituloError)
                    .addComponent(OkButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(TituloError)
                .addGap(18, 18, 18)
                .addComponent(TextoError, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OkButton)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_OkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ErrorCorreo dialog = new ErrorCorreo(new javax.swing.JFrame(), true, "ejemplo" );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkButton;
    private javax.swing.JLabel TextoError;
    private javax.swing.JLabel TituloError;
    // End of variables declaration//GEN-END:variables
}
