/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_pl2;

import clases_pl2.Actividad;
import clases_pl2.ActividadEspecial;
import clases_pl2.Horario;
import clases_pl2.Socio;
import clases_pl2.TipoActividad;

import java.time.LocalDate; // Formato de fecha moderno
import java.time.ZoneId;    // Para ayudar en la conversión de fechas
import java.util.Date;      // Formato de fecha del JSpinner
import javax.swing.JOptionPane; // Para mostrar mensajes emergentes
import persistencia.Gestor;

/**
 *
 * @author david
 */
public class ReservarActividad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservarActividad.class.getName());

    /**
     * Creates new form ReservarActividad
     */
    // Variables para guardar la información que recibimos
    private Actividad actividad;
    private Socio socio;

    /**
     * Nuevo constructor que recibe la Actividad y el Socio
     */
    public ReservarActividad(Actividad actividad, Socio socio) {
        this.actividad = actividad;
        this.socio = socio;
        
        initComponents(); // Carga la interfaz gráfica
        
        // Hacemos que al cerrar esta ventana no se cierre todo el programa
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        
        // Llamamos al método que rellena los JLabels
        cargarDatosDeReserva();
    }

    /**
     * Método para sustituir los "info" por la información real
     */
    private void cargarDatosDeReserva() {
        // Rellenamos los datos de la actividad
        jLabelActividad.setText(actividad.getTitulo());
        jLabelTipo.setText(String.valueOf(actividad.getTipo())); 
        jLabelMonitor.setText(actividad.getMonitor());
        jLabelSala.setText(actividad.getSala().getNombre());
        jLabelHorario.setText(actividad.getHorario().toString());
        
        // Rellenamos los datos del socio
        jLabelSocio.setText(socio.getNombre());
        
        // Calculamos el coste considerando si es especial y si el socio es VIP
        if (actividad.esEspecial()) {
            ActividadEspecial ae = (ActividadEspecial) actividad;
            // Usamos tu estupendo método calcularPrecio para aplicar el descuento si es necesario
            double precioFinal = socio.calcularPrecio(ae.getPrecio());
            jLabelCoste.setText(String.format("%.2f €", precioFinal));
        } else {
            jLabelCoste.setText("Incluido en tu cuota mensual");
        }
        
        // Un detalle extra para los días disponibles
        jLabelDiasDisponibles.setText("Horario original: " + actividad.getHorario().toString());
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelJavaFit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelActividad = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelMonitor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelSala = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelHorario = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelSocio = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelCoste = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelDiasDisponibles = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButtonCancelar = new javax.swing.JButton();
        jButtonReservar = new javax.swing.JButton();

        jLabel3.setText("Actividad:");

        jLabel4.setText("Actividad:");

        jLabel11.setText("Actividad:");

        jLabel12.setText("Actividad:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelJavaFit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelJavaFit.setText("JavaFit");

        jLabel1.setText("Actividad:");

        jLabelActividad.setText("info");

        jLabelTipo.setText("info");

        jLabel6.setText("Tipo:");

        jLabelMonitor.setText("info");

        jLabel8.setText("Monitor:");

        jLabelSala.setText("info");

        jLabel10.setText("Sala:");

        jLabelHorario.setText("info");

        jLabel14.setText("Horario:");

        jLabelSocio.setText("info");

        jLabel16.setText("Socio:");

        jLabelCoste.setText("info");

        jLabel18.setText("Coste:");

        jLabel20.setText("Fecha:");

        jLabelDiasDisponibles.setText("DIAS DISPONIBLES");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(this::jButtonCancelarActionPerformed);

        jButtonReservar.setText("Reservar");
        jButtonReservar.addActionListener(this::jButtonReservarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJavaFit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSala, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHorario, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoste, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1))
                    .addComponent(jLabelDiasDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReservar)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJavaFit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelActividad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelMonitor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelSala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelHorario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabelSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabelCoste))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDiasDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonReservar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        try {
            // 1. Obtener la fecha seleccionada en el JSpinner
            // El JSpinner devuelve un Object, así que lo "casteamos" a java.util.Date
            Date fechaSeleccionada = (Date) jSpinner1.getValue();
            
            // 2. Convertir java.util.Date a java.time.LocalDate
            LocalDate fechaLocal = fechaSeleccionada.toInstant()
                                      .atZone(ZoneId.systemDefault())
                                      .toLocalDate();
            
            // 3. Obtener la instancia de nuestro Gestor y procesar la reserva
            Gestor gestor = Gestor.getInstancia();
            
            // Este método lanzará un error si el aforo está lleno o el día es incorrecto
            gestor.crearReserva(socio, actividad, fechaLocal);
            
            // 4. Si todo ha ido bien, guardamos los datos permanentemente
            gestor.guardarDatos();
            
            // 5. Avisar al usuario del éxito y cerrar la ventana
            JOptionPane.showMessageDialog(this, 
                "¡Reserva confirmada con éxito para el " + fechaLocal + "!", 
                "Reserva Exitosa", 
                JOptionPane.INFORMATION_MESSAGE);
                
            this.dispose(); // Cierra solo esta ventana, manteniendo el menú principal abierto
            
        } catch (IllegalArgumentException ex) {
            // Aquí capturamos los mensajes que escribiste en el Gestor (ej: "No hay aforo")
            JOptionPane.showMessageDialog(this, 
                ex.getMessage(), 
                "No se pudo realizar la reserva", 
                JOptionPane.WARNING_MESSAGE);
                
        } catch (Exception ex) {
            // Si ocurre un error inesperado al guardar o procesar
            JOptionPane.showMessageDialog(this, 
                "Ocurrió un error inesperado: " + ex.getMessage(), 
                "Error Interno", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonReservarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelActividad;
    private javax.swing.JLabel jLabelCoste;
    private javax.swing.JLabel jLabelDiasDisponibles;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelJavaFit;
    private javax.swing.JLabel jLabelMonitor;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelSocio;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
